### ISSUE TITLE
elektra-web

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1314]
- [x] When doing `npm install` in clusterd, the first time I got `UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc`, redoing helped.
- [x] error handling missing in interface, see below
- [x] elektrify of tools themselves missing
- [ ] nodejs bindings missing
- [x] better README, e.g. where are clusters/nodes stored?
- [x] unclear when changes are applied
- [x] validation missing
- [x] gray text "webservers" makes you think, it is named "webservers" (should read: "enter name of cluster")
- [ ] cmake integration (run npm install while doing `make install`)
- [x] scripts to run elektrad+clusterd (also both for single-node usecase)
- [x] adding cluster/instance while configure interface is open?
- [x] when adding instance/cluster no further action was possible, needed to reload page

**Comment by markus2330** [comment]
error handling:
```
  clusterd:routes:clusters:error error while applying to all instances: Error: only absolute urls are supported
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:54:10
    at new Fetch (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:49:9)
    at Fetch (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:37:10)
    at Object.set (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/connector.js:46:34)
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/routes/clusters.js:149:38
    at Array.map (native)
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/routes/clusters.js:43:34
    at process._tickCallback (internal/process/next_tick.js:103:7) +3m
  clusterd:routes:clusters:error error while applying to all instances: Error: only absolute urls are supported
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:54:10
    at new Fetch (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:49:9)
    at Fetch (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/node_modules/node-fetch/index.js:37:10)
    at Object.set (/home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/connector.js:46:34)
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/routes/clusters.js:149:38
    at Array.map (native)
    at /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/build/routes/clusters.js:43:34
    at process._tickCallback (internal/process/next_tick.js:103:7) +20s

```

**Comment by omnidan** [comment]
-> #1839
