### ISSUE TITLE
can not install webservice

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1423]
It seems the install fails somehow... i followed the readme step by step ;)

```
~/libelektra/src/tools/web/elektrad$ npm install

npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@elektra-web/elektrad"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:266:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pkselfservice/libelektra/src/tools/web/elektrad
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pkselfservice/libelektra/src/tools/web/elektrad/npm-debug.log
npm ERR! not ok code 0
```

what could be the problem here?

edit: ohh is it the nodejs version? I need to install the one in stretch

**Comment by reox** [comment]
I updated to 4.7 but still get this error message?
```
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
```

**Comment by reox** [comment]
ok it works with 6.10.0

**Comment by markus2330** [comment]
@omnidan please update docu

**Comment by omnidan** [comment]
@markus2330 updated in 842eae7
