### ISSUE TITLE
libutility: sanitizer tests fail

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1440]
The website does not build anymore:

https://build.libelektra.org/job/elektra-homepage/lastFailedBuild/console

```
150/155 Test #150: test_utility .......................***Failed    0.22 sec
=================================================================
==16219==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffd722187f at pc 0x7fd4646699bd bp 0x7fffd72217e0 sp 0x7fffd72217a8
READ of size 1 at 0x7fffd722187f thread T0
    #0 0x7fd4646699bc in strcmp (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x369bc)
    #1 0x7fd465737ed1 in test_elektraRstrip /home/jenkins/workspace/workspace/elektra-homepage/tests/ctest/test_utility.c:36
    #2 0x7fd465735c9b in main /home/jenkins/workspace/workspace/elektra-homepage/tests/ctest/test_utility.c:97
    #3 0x7fd463168b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #4 0x7fd465735de3 (/home/jenkins/workspace/workspace/elektra-homepage/build/bin/test_utility+0x8de3)

Address 0x7fffd722187f is located in stack of thread T0 at offset 95 in frame
    #0 0x7fd465737c5f in test_elektraRstrip /home/jenkins/workspace/workspace/elektra-homepage/tests/ctest/test_utility.c:27

  This frame has 3 object(s):
    [32, 40) 'last'
    [96, 196) 'text' <== Memory access at offset 95 underflows this variable
    [256, 4352) 'errorMsg'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow ??:0 strcmp
Shadow bytes around the buggy address:
  0x10007ae3c2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c2c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c2d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c2e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c2f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007ae3c300: 00 00 00 00 f1 f1 f1 f1 00 f4 f4 f4 f2 f2 f2[f2]
  0x10007ae3c310: 00 00 00 00 00 00 00 00 00 00 00 00 04 f4 f4 f4
  0x10007ae3c320: f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ae3c350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==16219==ABORTING
```

**Comment by markus2330** [comment]
@sanssecours Is this only a test case issue or does `elektraRstrip` produce a faulty string?

**Comment by sanssecours** [comment]
> @sanssecours Is this only a test case issue or does elektraRstrip produce a faulty string?

As far as I can tell `elektraRstrip` returns an incorrect pointer inside `end`, if `start` points to an empty string. If we call `elektraRstrip (text, &last)` and `text` contains `""`, then `last` points to the location one character before `start` afterwards.
