### ISSUE TITLE
Ronn broken

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1476]
# Describe what you wanted to do

On arch:
mkdir build &&cd build
cmake .. && make

# Describe what you expected

A build

# Describe what actually happened

```
/usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:330:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:330:in `markdown_filter_heading_anchors'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:299:in `process_markdown!'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:210:in `markdown'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:290:in `input_html'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:305:in `process_html!'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:215:in `html'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:251:in `to_html_fragment'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:227:in `to_roff'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/lib/ronn/document.rb:221:in `convert'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/bin/ronn:202:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/bin/ronn:181:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/bin/ronn:181:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/bin/ronn:167:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/ronn-0.7.3/bin/ronn:167:in `<top (required)>'
        from /usr/bin/ronn:22:in `load'
        from /usr/bin/ronn:22:in `<main>'
make[2]: *** [doc/help/CMakeFiles/man-elektra-related.dir/build.make:61: doc/help/elektra-related.7] Error 1
make[2]: *** Deleting file 'doc/help/elektra-related.7'
```

- Elektra Version: master

# Further Information
 in the doc/help/elektra-related.md is the following line:

    which allows parts of Elektra’s global configuration tree to

changed to:

    which allows parts of Elektra's global configuration tree to

fixed this error but, git grep tells me that this issue is bigger:

```
git grep "Elektra’s"
elektra-algorithm.md:95:this number determined at the previous `kdbGet()`, Elektra’s core knows
elektra-algorithm.md:111:not tolerable to waste time or memory inside Elektra’s core, especially
elektra-algorithm.md:142:Elektra’s core will [pop](/doc/help/elektra-glossary.md) keys that are
elektra-algorithm.md:247:is needed.  Elektra’s core alone cannot check that because getting
elektra-algorithm.md:253:Elektra’s core can conform to C99.  Because the resolver plugin is the
elektra-architecture.md:109:Elektra’s core can be compiled with a C compiler conforming to the
elektra-classes.md:1:elektra classes(7) -- introduction to Elektra’s classes
elektra-classes.md:60:Elektra’s third class
elektra-contracts.md:33:with Elektra’s core. This topic will be discussed in
elektra-contracts.md:35:in which the algorithm used by Elektra’s core is explained.
elektra-contracts.md:58:postconditions imposed on data structures.  Elektra’s core provides
elektra-data-structures.md:232:For that reason, Elektra’s core does not provide
elektra-data-structures.md:268:Elektra’s private header files need to be included.
elektra-error-handling.md:101:- A **developer of the library** (Library refers to both Elektra’s core and plugins.)
elektra-error-handling.md:179:In Elektra’s core and plugins, C macros are responsible for setting
elektra-error-handling.md:215:that provide exceptions.  One design goal of Elektra’s error system is to transport
elektra-error-handling.md:245:be transformed to Elektra’s error or warning information.  The code for
elektra-faq.md:75:## What is the Elektra’s license?
elektra-granularity.md:33:To sum up, Elektra’s core searches for the nearest mountpoint and gets
elektra-plugins-framework.md:5:by calling methods of each other.  This is not the way Elektra’s plugin
elektra-plugins-framework.md:60:information.  Elektra’s core also uses the functions `elektraPluginSet()`,
elektra-plugins-framework.md:153:usually can choose which interfaces they implement.  Elektra’s plugins,
elektra-related.md:40:which allows parts of Elektra’s global configuration tree to
elektra-semantics.md:4:The use of arbitrary metadata has extensive effects in Elektra’s
elektra-semantics.md:17:Elektra’s Keys except for metakeys belonging to a key.  Every other Key is independent
elektra-semantics.md:52:If the backend `filesys` was the ideal solution, Elektra’s
kdb-editor.md:12:The `format` attribute relies on Elektra’s plugin system to properly import the configuration. The user can view all plugins available for use by running the kdb-list(1) command.
kdb-export.md:18:The `format` attribute relies on Elektra’s plugin system to export the keys in the desired format.The user can view all plugins available for use by running the kdb-list(1) command. To learn about any plugin, the user can simply use the kdb-info(1) command.  
kdb-export.md:44:To view your full key database in Elektra’s `storage` format:  
kdb-export.md:47:To backup your full key database in Elektra’s `storage` format to a file called `full-backup.ecf`:  
kdb-file.md:15:This command makes use of Elektra’s `resolver` plugin which the uer can learn more about by running the command `kdb info resolver`.
kdb-help.md:12:Show a man page for one of Elektra’s tools.
kdb-import.md:14:The `format` attribute relies on Elektra’s plugin system to properly import the configuration. The user can view all plugins available for use by running the kdb-list(1) command. To learn about any plugin, the user can simply use the kdb-info(1) command.
kdb-introduction.md:15:is part of Elektra’s tools and performs the mentioned tasks.
```

**Comment by markus2330** [comment]
Thank you for reporting the issue! This might be a regression from #1406? Can you try if setting RUBYOPT solves the issue? You might need to modify RUBYOPT in `doc/help/CMakeLists.txt`.

As quick workaround you can set BUILD_DOCUMENTATION to off.

**Comment by BernhardDenner** [comment]
Had the same issue, when building elektra in containers. Now I'm using a `export LANG=en_US.UTF-8` before starting the build.

**Comment by sanssecours** [comment]
@KurtMi Pull request #1477 should fix your issue. I already tested it on my machine. Could you please take a look if the problem is gone after you apply the changes?
