### ISSUE TITLE
crash when setting up signal

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1512]
# Describe what you wanted to do

Run all tests.

# Describe what you expected

That all tests run successfully.

# Describe what actually happened

```
Following test cases failed: 
testmod_mini
check_distribution
check_mount
check_resolver
```

The first one is a (separate) installation problem. The others crash because of how the signals are set up:

```
#0  0x00007f48f77c4067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f48f77c5448 in __GI_abort () at abort.c:89
#2  0x000000000044a620 in endl<char, std::char_traits<char> > (__os=...) at /usr/include/c++/4.9/ostream:565
#3  operator<< (__pf=<optimized out>, this=<optimized out>) at /usr/include/c++/4.9/ostream:113
#4  setupSignal (signum=<optimized out>) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/kdb/main.cpp:119
#5  <signal handler called>
#6  strlen () at ../sysdeps/x86_64/strlen.S:106
#7  0x000000000047203f in Cmdline::Cmdline (this=0x7fffbf8e3820, argc=10, argv=0x7fffbf8e3a18, command=0x1c92490) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/kdb/cmdline.cpp:407
#8  0x000000000041ac44 in _M_deallocate (this=<optimized out>, __n=18, __p=0x1c923f0) at /usr/include/c++/4.9/bits/stl_vector.h:177
#9  ~_Vector_base (this=0x7fffbf8e37d0, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:160
#10 ~vector (this=0x7fffbf8e37d0, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:425
#11 main (argc=10, argv=0x7fffbf8e3a18) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/kdb/main.cpp:205
```

# Possible Solution

We should use sigaction instead of signal. See also man pages, it is not portable what we are doing.

# System Information

- Elektra Version: master

**Comment by mpranj** [comment]
@markus2330 I assume this will stay relevant, even though things have been silent here.

**Comment by markus2330** [comment]
Yes but imho it is clearly a post-1.0 issue? If we simply let it stale out, we would also be able to find it later? I tagged it now with 2.0 and close it.
