### ISSUE TITLE
cmdline: crash

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1655]
When running: `kdb info -c classname=elektra/plugin/PropertiesStorage,classpath=.:/usr/share/java/jna.jar:/usr/lib/java:/path/to/libelektra/src/bindings/jna,print= jni`

There is a segfault (unrelated to jni, seems like -c does not accept arguments):
```
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff6822a84 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00005555555d636f in Cmdline::Cmdline (this=0x7fffffffdb90, argc=5, argv=0x7fffffffe398, command=0x5555558729c0) at /home/markus/Projekte/Elektra/current/src/tools/kdb/cmdline.cpp:459
#3  0x0000555555608ff1 in main (argc=5, argv=0x7fffffffe398) at /home/markus/Projekte/Elektra/current/src/tools/kdb/main.cpp:168
```

**Comment by markus2330** [comment]
fixed with a04a7b1dcef3355f27ed0bb2bf00d55918f2930f
(and the jni plugin seems to work with java 9)

```
> LD_LIBRARY_PATH=`pwd`/lib:/usr/lib/jvm/java-9-openjdk-amd64/lib:/usr/lib/jvm/java-9-openjdk-amd64/lib/server bin/kdb info -c classname=elektra/plugin/PropertiesStorage,classpath=.:/usr/share/java/jna.jar:/usr/lib/java:/path/to/libelektra/src/bindings/jna,print= jni
Module does not seem to be loaded.
Now in fallback code. Will directly load config from plugin.
The command bin/kdb info terminated unsuccessfully with the info:
Was not able to load such a plugin!

Maybe you misspelled it, there is no such plugin or the loader has problems.
You might want to try to set LD_LIBRARY_PATH, use kdb-full or kdb-static.
Errors/Warnings during loading were:
Sorry, the error (#102) occurred ;(
Description: jni/java error
Ingroup: plugin
Module: jni
At: /home/markus/Projekte/Elektra/current/src/plugins/jni/jni.c:236
Reason: Cannot find class elektra/plugin/PropertiesStorage
Mountpoint: 
Configfile: 
 Sorry, 1 warning was issued ;(
 Warning (#11):
        Description: open of plugin returned unsuccessfully (reason contains plugin, see other warnings for details)
        Ingroup: kdb
        Module: 
        At: /home/markus/Projekte/Elektra/current/src/libs/elektra/plugin.c:294
        Reason: jni
        Mountpoint: 
        Configfile: 

Please report the issue at https://issues.libelektra.org/
```
