### ISSUE TITLE
Build Jobs Failing due to timeout

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1689]
Seems we have quite many timeouts in the buildjobs, e.g.:
https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch/lastFailedBuild/console
https://build.libelektra.org/jenkins/job/elektra-homepage/lastFailedBuild/console

with errors like:

```
FATAL: command execution failed
hudson.remoting.ProxyException: java.util.concurrent.TimeoutException: Ping started at 1509550735761 hasn't completed by 1509550985064
Caused: Command close created at
	at hudson.remoting.Command.<init>(Command.java:60)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1216)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1214)
	at hudson.remoting.Channel.close(Channel.java:1389)
	at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:180)
	at hudson.remoting.PingThread.ping(PingThread.java:130)
	at hudson.remoting.PingThread.run(PingThread.java:86)
Caused: hudson.remoting.Channel$OrderlyShutdown: hudson.remoting.ProxyException: java.util.concurrent.TimeoutException: Ping started at 1509550735761 hasn't completed by 1509550985064
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1222)
	at hudson.remoting.Channel$1.handle(Channel.java:557)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:83)
Caused: java.io.IOException: Backing channel 'debian-stretch-mr' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:192)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
	at com.sun.proxy.$Proxy71.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Build step 'Execute shell' marked build as failure
```

Some ideas how to deal with it:
https://support.cloudbees.com/hc/en-us/articles/115001369667-dedicated-SSH-agents-formerly-slaves-get-disconnected

Or by changing the ping interval:
System.setProperty("hudson.slaves.ChannelPinger.pingInterval", "0")

Anyone wants to take this issue?

**Comment by markus2330** [comment]
problem does not occur anymore
