### ISSUE TITLE
swig_ruby: Failing tests

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#1770]
## Steps to Reproduce the Problem

PR #1515 introduces the plugin syntax for the `BINDING` CMake variable. We decided to use `MAINTAINED;-EXPERIMENTAL;-DEPRECATED` as default. As a result `swig_ruby` was built by several build jobs, but some tests failed.

From https://build.libelektra.org/jenkins/job/elektra-homepage/293/consoleFull
```
        Start  33: testruby_key
 30/114 Test  #33: testruby_key .....................***Failed    1.08 sec
==7346==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

From https://build.libelektra.org/jenkins/job/elektra-clang-asan/351/consoleFull:
```
        Start  32: testruby_kdb
 32/176 Test  #32: testruby_kdb ............................***Failed    0.07 sec
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /home/jenkins/workspace/workspace/elektra-clang-asan/build/lib/libelektra-core.so.4: undefined symbol: __asan_option_detect_stack_use_after_return - /home/jenkins/workspace/workspace/elektra-clang-asan/build/src/bindings/swig/ruby/_kdb.so (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jenkins/workspace/workspace/elektra-clang-asan/src/bindings/swig/ruby/kdb.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jenkins/workspace/workspace/elektra-clang-asan/src/bindings/swig/ruby/tests/testruby_kdb.rb:10:in `<main>'
```

From https://build.libelektra.org/jenkins/job/elektra-gcc-configure-xdg/926/consoleFull
```
        Start  37: testruby_tools_plugindatabase
 37/116 Test  #37: testruby_tools_plugindatabase ...........***Failed    0.20 sec
Loaded suite /home/jenkins/workspace/workspace/elektra-gcc-configure-xdg/src/bindings/swig/ruby/tests/testruby_tools_plugindatabase
Started
KdbtoolsPluginDatabaseTestCases: 
  test_get_int_pluginspec_map:				F
===============================================================================
Failure:
  Exception raised:
  Kdbtools::ToolException(<Kdbtools::ToolException>)
test_get_int_pluginspec_map(KdbtoolsPluginDatabaseTestCases)
/home/jenkins/workspace/workspace/elektra-gcc-configure-xdg/src/bindings/swig/ruby/tests/testruby_tools_plugindatabase.rb:72:in `test_get_int_pluginspec_map'
     69:   end
     70: 
     71:   def test_get_int_pluginspec_map
  => 72:     assert_nothing_raised do
     73:       db = Kdbtools::ModulesPluginDatabase.new
     74: 
     75:       ps = db.lookup_all_provides_with_status "ini"

```

The first two issues are related to ASAN, the third might be unrelated.

I was able to reproduce the second issue locally using `clang-3.8` and `ENABLE_ASAN`.

## System Information

- Elektra Builds: `elektra-homepage`, `elektra-gcc-configure-xdg` and `elektra-clang-asan`.

**Comment by waht** [comment]
@BernhardDenner please take a look.
