### ISSUE TITLE
crash in spec plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1821]
## Steps to Reproduce the Problem

Create a file /usr/share/elektra/specification/default.ecf with the content:
```
[tests/tutorial/cascading/#0/current]
#@META override/#0 = /tests/overrides/test
test =
```

and a ~/.config/default.ecf with the content:
```
[]
```
(or more) and run any kdb command, e.g. `kdb ls /`.

## Expected Result

Usual behavior of command.

## Actual Result

Segmentation fault:
```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff6ca1c0f in __fnmatch (pattern=<optimized out>, pattern@entry=0x555555836100 "tests/tutorial/cascading/#0/current", string=<optimized out>, flags=flags@entry=1) at fnmatch.c:451
#2  0x00007ffff4e73cd8 in matchPatternToKey (key=0x555555834080, pattern=0x555555836100 "tests/tutorial/cascading/#0/current") at ./src/plugins/spec/spec.c:85
#3  doGlobbing (parentKey=parentKey@entry=0x55555580ec20, returned=returned@entry=0x5555558360c0, specKS=specKS@entry=0x555555835540, ch=ch@entry=0x55555583f2d0, dir=dir@entry=GET, clean=clean@entry=0) at ./src/plugins/spec/spec.c:680
#4  0x00007ffff4e74a00 in elektraSpecGet (handle=0x5555558407a0, returned=0x555555827ce0, parentKey=0x55555580ec20) at ./src/plugins/spec/spec.c:873
#5  0x00007ffff50793b3 in runPlugins (pluginKS=pluginKS@entry=0x55555583de40, modules=0x55555582a030, plugins=0x555555829f60, configOrig=0x55555583f5d0, returned=returned@entry=0x555555827ce0, parentKey=parentKey@entry=0x55555580ec20, op=GET, 
    traversalFunction=0x7ffff751f690 <ksNext>) at ./src/plugins/list/list.c:301
#6  0x00007ffff50796ca in elektraListGet (handle=<optimized out>, returned=0x555555827ce0, parentKey=0x55555580ec20) at ./src/plugins/list/list.c:337
#7  0x00007ffff772d871 in kdbGet (handle=<optimized out>, ks=0x555555827ce0, parentKey=0x55555580ec20) at ./src/libs/elektra/kdb.c:889
#8  0x0000555555583f80 in kdb::KDB::get (parentKey=..., returned=..., this=0x7fffffffd950) at ./src/bindings/cpp/include/kdb.hpp:183
#9  kdb::KDB::get (keyname="/sw/kdb/current/", returned=..., this=0x7fffffffd950) at ./src/bindings/cpp/include/kdb.hpp:166
#10 Cmdline::Cmdline (this=0x7fffffffe1b0, argc=3, argv=0x7fffffffe508, command=0x55555580e990) at ./src/tools/kdb/cmdline.cpp:302
#11 0x0000555555575196 in main (argc=3, argv=0x7fffffffe508) at ./src/tools/kdb/main.cpp:168
```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
@tom-wa: please create a PR with ee07f05
