### ISSUE TITLE
multiresolver: crashes on some file names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2124]
## Steps to Reproduce the Problem

```sh
kdb mount -R multifile -c storage="ini",pattern="*",resolver="resolver" "`pwd`" "system/here" 
touch \(\\
kdb ls system/here
```
## Expected Result

List content of files.

## Actual Result

```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f1f5afd542a in __GI_abort () at abort.c:89
#2  0x00005611a6360b2c in catchSignal (signum=<optimized out>) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/tools/kdb/main.cpp:110
#3  <signal handler called>
#4  libelektra_resolver_fm_hpu_b_LTX_elektraPluginget (handle=0x5611a6d627a0, returned=0x5611a6cb4430, parentKey=0x5611a6c198c0)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/plugins/resolver/resolver.c:506
#5  0x00007f1f59015c77 in resolverGet (parentKey=0x5611a6c198c0, returned=0x5611a6cb4430, s=0x5611a6d62360)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/plugins/multifile/multifile.c:316
#6  updateFiles (parentKey=<optimized out>, returned=0x5611a6cb4430, mc=0x5611a6c0c620) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/plugins/multifile/multifile.c:487
#7  elektraMultifileGet (handle=0x5611a6c0e950, returned=0x5611a6cb4430, parentKey=<optimized out>)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/plugins/multifile/multifile.c:611
#8  0x00007f1f5baede20 in elektraGetCheckUpdateNeeded (parentKey=<optimized out>, split=<optimized out>)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/libs/elektra/kdb.c:468
#9  kdbGet (handle=0x5611a6be8aa0, ks=ks@entry=0x5611a6c178b0, parentKey=0x5611a6c198c0) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/libs/elektra/kdb.c:804
#10 0x00005611a633049f in kdb::KDB::get (parentKey=..., returned=<synthetic pointer>..., this=0x5611a6be8a38)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/bindings/cpp/include/kdb.hpp:183
#11 CpCommand::execute (this=0x5611a6be8a30, cl=...) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/tools/kdb/cp.cpp:57
#12 0x00005611a6314d14 in main (argc=<optimized out>, argv=0x7ffe9315a238) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/libelektra/src/tools/kdb/main.cpp:198
```

Seems like the resolver is not correctly initialized in such cases, maybe kdbOpen() is not called?

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
@tom-wa any progress here?
