### ISSUE TITLE
Homepage: Current Version of Homepage Does Not Reflect State of  Branch `master`

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2252]
# Problem Description

It looks like the current version of the homepage does not contain all updates of the current `master` branch. For example,

- the [plugin page](https://www.libelektra.org/plugins/readme) does neither list the [YAmbi](https://www.libelektra.org/plugins/yambi) plugin, nor the [`mmapstorage` plugin](https://www.libelektra.org/plugins/mmapstorage),
- the [ReadMe of the network plugin](https://www.libelektra.org/plugins/network) does not mention the  recently added support for domain names

. Is this intentional behavior?

**Comment by mpranj** [comment]
It is not intentional, thanks for catching this! The [homepage build](https://build.libelektra.org/jenkins/job/elektra-homepage/) did not succeed for a while, so the homepage was not published. The build has ASan enabled, and `testmod_dbus` is [failing](https://build.libelektra.org/jenkins/job/elektra-homepage/523/consoleFull).

**Comment by markus2330** [comment]
Thank you for reporting! It seems like #2118 did not fix this problem. @waht do you have an idea what the problem now is?

**Comment by markus2330** [comment]
Error log is:

```
 52/115 Test  #61: testmod_dbus .....................***Failed    0.82 sec
process 18840: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../../dbus/dbus-connection.c line 2824.
This is normally a bug in some application using the D-Bus library.

=================================================================
==18840==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 4239 byte(s) in 5 object(s) allocated from:
    #0 0x7fefc0b77090 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2090)
    #1 0x7fefc067878c  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x3078c)

Indirect leak of 404 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc067859c in _dbus_mem_pool_alloc (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x3059c)

Indirect leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc065a72d  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x1272d)

Indirect leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc0657c67  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0xfc67)

Indirect leak of 232 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc06746df  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x2c6df)

Indirect leak of 224 byte(s) in 4 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc065f4ad in _dbus_credentials_new (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x174ad)

Indirect leak of 176 byte(s) in 2 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc066d4ea  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x254ea)

Indirect leak of 160 byte(s) in 4 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc067e841  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x36841)

Indirect leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc06756fb in _dbus_hash_table_new (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x2d6fb)

Indirect leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc066a65f in _dbus_message_loader_new (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x2265f)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc067e961  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x36961)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc067e7ea  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x367ea)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc066be57  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x23e57)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b77090 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2090)
    #1 0x7fefc066a7e1 in _dbus_message_loader_get_unix_fds (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x227e1)
    #2 0x3fdf9fc4991cc8ff  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc065a6e7  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x126e7)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc065a6f8  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x126f8)

Indirect leak of 42 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc0678c99 in _dbus_string_copy_data (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x30c99)
    #2 0x3fdf9fc4991cc8ff  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc0678443 in _dbus_mem_pool_new (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x30443)

Indirect leak of 32 byte(s) in 4 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc06789d3  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x309d3)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc066c272  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x24272)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7fefc0658791  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x10791)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b77090 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc2090)
    #1 0x7fefc0675554  (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x2d554)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7fefc0b76d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7fefc067648e in _dbus_strdup (/lib/x86_64-linux-gnu/libdbus-1.so.3+0x2e48e)

SUMMARY: AddressSanitizer: 6731 byte(s) leaked in 39 allocation(s).

        Start  63: testmod_directoryvalue
```
