### ISSUE TITLE
qt-gui: crash on binary keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#234]
The metadata "binary" seems to cause trouble. Its possible to crash the gui when it is added or removed.

Its not possible to add it (seems to be a more general issue that meta keys with empty values are not allowed):

```
qrc:/qml/KeyWindow.qml:21: TypeError: Cannot read property 'path' of null
```

e.g. a stack trace (caused by removing the metadata of a binary key):

```
#0  0x00007f2e85108367 in keyIncRef (key=0x4030000000000000) at /home/markus/Projekte/Elektra/current/src/libelektra/key.c:558
#1  0x000000000042fecb in kdb::Key::operator++ (this=0x7fffcdfba000) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/key.hpp:594
#2  0x000000000043fa90 in kdb::Key::Key (this=0x7fffcdfba000, k=...) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/key.hpp:517
#3  0x000000000044db53 in ConfigNode::getKey (this=0x7f2e742b7d50) at /home/markus/Projekte/Elektra/current/src/tools/qt-gui/src/confignode.cpp:197
#4  0x0000000000438096 in TreeViewModel::data (this=0x2673e60, idx=..., role=267) at /home/markus/Projekte/Elektra/current/src/tools/qt-gui/src/treeviewmodel.cpp:93
#5  0x000000000043add0 in TreeViewModel::get (this=0x2673e60, idx=@0x7fffcdfba568: 0) at /home/markus/Projekte/Elektra/current/src/tools/qt-gui/src/treeviewmodel.cpp:310
#6  0x0000000000455e87 in TreeViewModel::qt_static_metacall (_o=0x2673e60, _c=QMetaObject::InvokeMetaMethod, _id=11, _a=0x7fffcdfba6c0) at /home/markus/Projekte/Elektra/build/src/tools/qt-gui/moc_treeviewmodel.cpp:185
#7  0x0000000000456610 in TreeViewModel::qt_metacall (this=0x2673e60, _c=QMetaObject::InvokeMetaMethod, _id=11, _a=0x7fffcdfba6c0) at /home/markus/Projekte/Elektra/build/src/tools/qt-gui/moc_treeviewmodel.cpp:265
```

**Comment by markus2330** [comment]
the exception text is:
```
terminate called after throwing an instance of 'kdb::KeyTypeMismatch'
  what():  Binary/String key mismatch, use proper getString()/getBinary() or use getValue() to get both.
```

Another backtrace:
```
#5  0x00007fb8f9537bee in __cxxabiv1::__cxa_throw (obj=0x2cad8a0, tinfo=<optimized out>, dest=<optimized out>) at ../../../../src/libstdc++-v3/libsupc++/eh_throw.cc:83
#6  0x00000000004301f3 in kdb::Key::getString (this=0x7fff45e164e0) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/key.hpp:1170
#7  0x00007fb8f9d7c1d7 in kdb::tools::merging::AutoMergeStrategy::resolveConflict (this=0x2d91870, task=..., conflictKey=..., result=...) at /home/markus/Projekte/Elektra/current/src/libtools/src/merging/automergestrategy.cpp:41
#8  0x00007fb8f9d7e55e in kdb::tools::merging::ThreeWayMerge::mergeKeySet (this=0x7fff45e166d0, task=...) at /home/markus/Projekte/Elektra/current/src/libtools/src/merging/threewaymerge.cpp:163
#9  0x000000000043d124 in TreeViewModel::synchronize (this=0x7fff45e19ff0) at /home/markus/Projekte/Elektra/current/src/tools/qt-gui/src/treeviewmodel.cpp:571
#10 0x0000000000455f35 in TreeViewModel::qt_static_metacall (_o=0x7fff45e19ff0, _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fff45e16cd0) at /home/markus/Projekte/Elektra/build/src/tools/qt-gui/moc_treeviewmodel.cpp:189
#11 0x0000000000456610 in TreeViewModel::qt_metacall (this=0x7fff45e19ff0, _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fff45e16cd0) at /home/markus/Projekte/Elektra/build/src/tools/qt-gui/moc_treeviewmodel.cpp:265
```

**Comment by markus2330** [comment]
the crash should be fixed. Support for binary keys is not needed.

**Comment by markus2330** [comment]
@0003088 Do you have some time to fix the crash? Not really important if the user can edit binary data, but the gui should not crash nor lose data.

**Comment by 0003088** [comment]
I'll see what I can do ...

**Comment by 0003088** [comment]
I'm really sorry for the long delay. Could you please be more specific in how to trigger the crash? Removing  the binary metakey from e.g 'system/elektra/modules/dump/exports/get' doesn't do anything?

**Comment by markus2330** [comment]
Thanks for looking into the issue!

First off: our Debian packages now contains qt-gui, so qt-gui has a much larger user base now!

The command-line tooling is not really able to create binary keys, but it is possible to reproduce it only using the qt-gui:

1. right click on user -> new key
2. Fill out Key Name: abc, Key Value: abc
3. Press "New Meta Key"; with meta key name: "binary" (no quotes), meta key value: (do not enter text)
4. Press "Ok"
5. Click on newly created binary key -> Edit
6. add a character after "abc " -> "abc a" (the character we do not see here is a null byte)
7. press "Ok" ->  Crash :cry: 

So you basically create a binary key and change its value. Pressing synchronization is not necessary.

The backtrace then is:
```
#0  0x00007f4ac5175067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f4ac5176448 in __GI_abort () at abort.c:89
#2  0x00007f4ac5761b3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f4ac575fbb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f4ac575fc01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f4ac575fe19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000043ab86 in getString (this=0x3868f00) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/bindings/cpp/include/key.hpp:1252
#7  ConfigNode::setValue (this=this@entry=0x3868ed0, value=...) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/qt-gui/src/confignode.cpp:121
#8  0x000000000041af6e in TreeViewModel::setData (this=0x3868500, idx=..., modelData=..., role=role@entry=259) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/qt-gui/src/treeviewmodel.cpp:156
#9  0x000000000043744c in EditKeyCommand::redo (this=0x4bee770) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/qt-gui/src/editkeycommand.cpp:30
#10 0x00007f4ac6c0afc8 in QUndoStack::push(QUndoCommand*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x000000000042d169 in UndoManager::createEditKeyCommand (this=<optimized out>, model=<optimized out>, idx=<optimized out>, data=<optimized out>) at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/tools/qt-gui/src/undomanager.cpp:40
#12 0x00000000004405d9 in UndoManager::qt_static_metacall (_o=_o@entry=0x7ffdf21e0090, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=9, _a=_a@entry=0x7ffdf21dd420)
    at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/obj-x86_64-linux-gnu/src/tools/qt-gui/moc_undomanager.cpp:186
#13 0x0000000000443d67 in UndoManager::qt_metacall (this=0x7ffdf21e0090, _c=QMetaObject::InvokeMetaMethod, _id=9, _a=0x7ffdf21dd420)
    at /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/obj-x86_64-linux-gnu/src/tools/qt-gui/moc_undomanager.cpp:333
#14 0x00007f4ac71a9aae in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#15 0x00007f4ac71ac8ec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#16 0x00007f4ac71acf53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007f4ac71b69a6 in QV4::Runtime::callProperty(QV4::ExecutionContext*, QV4::StringRef, QV4::CallDataRef) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007f4ab801eefb in ?? ()
#19 0x00007ffdf21dda30 in ?? ()
#20 0x00007f4ac7259c72 in QV4::QmlContextWrapper::get(QV4::Managed*, QV4::StringRef, bool*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007f4ab2e3c1b8 in ?? ()
#22 0x0000000001b68740 in ?? ()
#23 0x00007ffdf21ddcc0 in ?? ()
#24 0x00007f4aa8aca100 in ?? ()
#25 0x0000000000000000 in ?? ()
```

Btw. it is okay to not support it, but the gui should not crash. Simply show an error in such cases.

**Comment by 0003088** [comment]
What would be a sufficient error message in this case? E.g. 'Creating/Editing binary keys is not yet supported' or something to that effect?

**Comment by markus2330** [comment]
Yes, that sounds great!
