### ISSUE TITLE
multiresolver: crash on failed commits

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2527]
## Steps to Reproduce the Problem

Mount a multi-file resolver, e.g.

```sh
kdb mount -R multifile -c storage="ini",pattern="*",resolver="resolver" `pwd`/folder system/something
```

then do a kdbGet(), externally modify a file, then do kdbSet()

In my case a python program did the kdbGet() and later kdbSet(), and a `git checkout -f` did the modification of the files, but this should not matter.

## Expected Result

That a conflict occurs.

## Actual Result

A crash occurs:

```
#6  0x00007f7a78820234 in elektraUnlinkFile (filename=0x746e65647574732f <error: Cannot access memory at address 0x746e65647574732f>, parentKey=parentKey@entry=0x5642f7521f50) at ./src/plugins/resolver/resolver.c:1109
#7  0x00007f7a78821bd5 in libelektra_resolver_fm_hpu_b_fm_hpu_b_LTX_elektraPluginerror (handle=<optimized out>, r=<optimized out>, parentKey=0x5642f7521f50) at ./src/plugins/resolver/resolver.c:1125
#8  0x00007f7a75f81acd in elektraMultifileError (handle=0x5642e9ef76d0, returned=0x5642f7522280, parentKey=0x5642f7521f50) at ./src/plugins/multifile/multifile.c:876
#9  0x00007f7a79771026 in elektraSetRollback (parentKey=0x5642f7521f50, split=0x5642f7522240) at ./src/libs/elektra/kdb.c:1081
#10 kdbSet (handle=0x5642e9e5acf0, ks=0x5642e9dec440, parentKey=0x5642f7521f50) at ./src/libs/elektra/kdb.c:1302
#11 0x00007f7a799a40b9 in kdb::KDB::set (parentKey=..., returned=..., this=0x5642e9e228e0) at ./src/bindings/cpp/include/kdb.hpp:227
#12 kdb::KDB::set (keyname="system/lehre/ep2/students", returned=..., this=0x5642e9e228e0) at ./src/bindings/cpp/include/kdb.hpp:208
#13 _wrap_KDB_set__SWIG_0 (swig_obj=0x7ffff3dec2b0, nobjs=3) at ./obj-x86_64-linux-gnu/src/bindings/swig/python2/kdbPYTHON_wrap.cxx:9637
#14 _wrap_KDB_set (self=<optimized out>, args=<optimized out>) at ./obj-x86_64-linux-gnu/src/bindings/swig/python2/kdbPYTHON_wrap.cxx:9725
```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
It would be good if we somehow document that stale bugs exist for some plugin, so that people do not have wrong expectations on them.

Maybe we should also add a "stale" tag for plugins (see #666)?

**Comment by mpranj** [comment]
You're absolutely right, for Elektra users it would make sense to introduce a tag. I don't think many people will search through all issues to find whether a bug was already reported. They will definitely not find these stale and closed issues.
