### ISSUE TITLE
Type: Mount Command from ReadMe Causes Segmentation Fault

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2602]
# Steps to Reproduce the Problem

1. Build Elektra
2. Execute the following command from the [ReadMe of the type plugin](https://www.libelektra.org/plugins/type):

   ```sh
   kdb mount typetest.dump       \
             user/tests/type     \
             dump type           \
             booleans=#1         \
             booleans/#0/true=a  \
             booleans/#0/false=b \
             booleans/#1/true=t  \
             booleans/#1/false=f
   ```

# Expected Result

The command above should succeed without any problems.

# Actual Result

The last command produces a segmentation fault:

```
Sorry, I crashed by the signal SIGSEGV
This should not have happened!

Please report the issue at https://issues.libelektra.org/
fish: 'kdb mount typetest.dump user/te…' terminated by signal SIGABRT (Abort)
```

.

# System Information

- Elektra Version: `master`
- macOS `10.14.4`

**Comment by markus2330** [comment]
Thank you for reporting this bug!

We should add the file to the shell recorder tests.

Backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff6e187842a in __GI_abort () at abort.c:89
#2  0x000055ead4b7e53c in catchSignal (signum=<optimized out>) at ./src/tools/kdb/main.cpp:110
#3  <signal handler called>
#4  readBooleans (config=config@entry=0x55ead60e2470, result=result@entry=0x55ead60e4f68, errorKey=errorKey@entry=0x55ead611b100) at ./src/plugins/type/type.c:184
#5  0x00007ff6d7964bb4 in elektraTypeOpen (handle=0x55ead60e1c90, errorKey=0x55ead611b100) at ./src/plugins/type/type.c:200
#6  0x00007ff6e239cbc2 in elektraPluginOpen (name=0x7ffe2b0d3e20 "type", modules=modules@entry=0x55ead60dbc10, config=0x0, config@entry=0x55ead60e2470, errorKey=errorKey@entry=0x55ead611b100) at ./src/libs/elektra/plugin.c:294
#7  0x00007ff6e25e9fa1 in kdb::tools::Plugin::Plugin (this=0x55ead611b280, spec_=..., modules=...) at ./src/libs/tools/src/plugin.cpp:39
#8  0x00007ff6e25e815e in kdb::tools::Modules::load (this=this@entry=0x55ead60dcce0, spec=...) at ./src/libs/tools/src/modules.cpp:49
#9  0x00007ff6e25e8271 in kdb::tools::Modules::load (this=0x55ead60dcce0, pluginName="type", config=...) at ./src/libs/tools/src/modules.cpp:44
#10 0x00007ff6e25f5597 in kdb::tools::ModulesPluginDatabase::getSymbol (this=this@entry=0x55ead60e85e0, spec=..., which="checkconf") at ./src/libs/tools/src/plugindatabase.cpp:227
#11 0x00007ff6e25d28bc in kdb::tools::BackendBuilder::addPlugin (this=0x7ffe2b0d45f0, plugin=...) at ./src/libs/tools/src/backendbuilder.cpp:440
#12 0x000055ead4b8bd4b in kdb::tools::BackendBuilder::addPlugins (plugins=std::vector of length 2, capacity 2 = {...}, this=0x7ffe2b0d45f0) at ./src/libs/tools/include/backendbuilder.hpp:140
#13 MountCommand::buildBackend (this=this@entry=0x55ead601ed00, cl=...) at ./src/tools/kdb/mount.cpp:169
#14 0x000055ead4b8daf8 in MountCommand::execute (this=0x55ead601ed00, cl=...) at ./src/tools/kdb/mount.cpp:286
#15 0x000055ead4b306d9 in main (argc=<optimized out>, argv=0x7ffe2b0d4ed8) at ./src/tools/kdb/main.cpp:198
```

So it seems like some bug in the type plugin.

**Comment by kodebach** [comment]
Did you try putting quotes around the #, in case your shell treats it as the start of a comment?

**Comment by markus2330** [comment]
I tried now. It still segfaults.

And even if the boolean specification is wrong, it should never segfault.
