### ISSUE TITLE
failing test cases in python2 iterator and copy

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#271]
```
        Start  34: testpy2_keyset.py
 34/108 Test  #34: testpy2_keyset.py ..................***Failed    0.02 sec
....E
======================================================================
ERROR: test_python_copy (__main__.KeySet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markus/Projekte/Elektra/current/src/bindings/swig/python2/tests/testpy2_keyset.py", line 119, in test_python_copy
    ks = copy.deepcopy(self.ks)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(SwigPyObject) is not safe, use SwigPyObject.__new__()

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)

        Start  35: testpy2_kdb.py
 35/108 Test  #35: testpy2_kdb.py .....................   Passed    0.03 sec
        Start  36: testpy2_key.py
 36/108 Test  #36: testpy2_key.py .....................***Failed    0.02 sec
..E...F
======================================================================
ERROR: test_iterator (__main__.Key)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markus/Projekte/Elektra/current/src/bindings/swig/python2/tests/testpy2_key.py", line 153, in test_iterator
    self.assertEqual(sum(1 for _ in k),           3)
TypeError: 'Key' object is not iterable

======================================================================
FAIL: test_python_copy (__main__.Key)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markus/Projekte/Elektra/current/src/bindings/swig/python2/tests/testpy2_key.py", line 149, in test_python_copy
    self.assertNotEqual(k, self.key)
AssertionError: <kdb.Key; proxy of <Swig Object of type 'kdb::Key *' at 0x7f0791b1d4b0> > == <kdb.Key; proxy of <Swig Object of type 'kdb::Key *' at 0x7f0791b1d4b0> >

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
```

**Comment by manuelm** [comment]
copy works here.

Iterators are indeed not implemented/copied. I'll remove this feature from python2. It is legacy and I won't implement the elektra plugin for python2 anyway.

**Comment by manuelm** [comment]
Edit: Scratch that. The cmake dependencies for python2 are broken (your building lot).

Just recompile the whole python2 plugin.

**Comment by markus2330** [comment]
Sorry for the noise, removing build directory helped. I wrote a note in the README.md that removing build directory is sometimes needed.
