### ISSUE TITLE
ronn fails on debian buster

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2883]
```
warn: unrecognized inline tag: ["img"]
Traceback (most recent call last):
        23: from /usr/bin/ronn:184:in `<main>'
        22: from /usr/bin/ronn:184:in `each'
        21: from /usr/bin/ronn:199:in `block in <main>'
        20: from /usr/bin/ronn:199:in `each'
        19: from /usr/bin/ronn:220:in `block (2 levels) in <main>'
        18: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:240:in `convert'
        17: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `to_roff'
        16: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `new'
        15: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:18:in `initialize'
        14: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:91:in `block_filter'
        13: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
        12: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:203:in `each'
        11: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:203:in `upto'
        10: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:204:in `block in each'
         9: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
         8: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:120:in `block_filter'
         7: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `inline_filter'
         6: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:203:in `each'
         5: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:203:in `upto'
         4: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:204:in `block in each'
         3: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `block in inline_filter'
         2: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `inline_filter'
         1: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `write'
/usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `gsub': incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) (Encoding::CompatibilityError)
```

**Comment by markus2330** [comment]
Seems to be a known issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928627 but no answer since May.

And ronn upstream is dead: https://github.com/rtomayko/ronn/issues/103

The problem seems to be only in line 354, commenting it out, and all man pages build:

`text = text.gsub(/\n\\\./s, "\n\\\\&\\.")`

@sanssecours did you try to use ronn 0.8.0? (I would be interested if ruby or ronn is the problem here)

**Comment by sanssecours** [comment]
> @sanssecours did you try to use ronn 0.8.0?

Nope. I just use the official `ronn` gem, which is still at version `0.7.3` and seems to work fine, even with an up-to-date version of Ruby (`2.6.3p62`).

**Comment by markus2330** [comment]
Yes, ronn 0.7.3 does not have this problems. So lets stick with that. I keep this issue open for documentation purposes. (Also the comment in scripts/docker/debian/stretch/doc.Dockerfile is wrong: It has the `ronn` executable but it does not work with the output above)

What a rare situation that Debian is more up-to-date :small_airplane:

**Comment by markus2330** [comment]
Solution: we only support  ronn 0.7.3. We should document that. Ideally, we would add a version check.
