### ISSUE TITLE
Jenkins: Daily Cleanup Task Fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2994]
# Description

Since [build 596 of `libelektra-daily`](https://build.libelektra.org/jenkins/job/libelektra-daily/569/) was stuck for over 1 day – the usual execution time is about 10 minutes – I canceled the task. Recent executions of `libelektra-daily` now [seem to fail on the build server `v2`](https://build.libelektra.org/jenkins/job/libelektra-daily/571/console):

```
java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on v2-debian-buster failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:948)
	at hudson.EnvVars.getRemote(EnvVars.java:408)
	at hudson.model.Computer.getEnvironment(Computer.java:1188)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:691)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

.

**Comment by markus2330** [comment]
@Mistreated @ingwinlu Do you have an idea what this could be?

**Comment by markus2330** [comment]
I started libelektra-daily manually now (after making space on v2)

**Comment by markus2330** [comment]
I stopped v2 and restarted libelektra-daily again. Seems like something is still damaged on v2.

**Comment by markus2330** [comment]
libelektra-daily was working, I now try with new Docker version on v2.

**Comment by markus2330** [comment]
Also the daily fails: https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra-daily/detail/libelektra-daily/577/pipeline

**Comment by markus2330** [comment]
Failed again, even with completely fresh docker. So maybe it is a network problem? (ssh tunnels unstable or similar)

**Comment by markus2330** [comment]
libelektra-daily now succeeded on v2!

The solution seems to be to remove /home/jenkins

I now did the same with i7. Let us hope this brings more stability again.

**Comment by markus2330** [comment]
Can we close this now?

Some garbage in /home/jenkins seems to be the reason for this problem.
