### ISSUE TITLE
Cirrus: Installing ronn fails 

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3193]
Since merging master into #3106 I get the following error ([full log](https://cirrus-ci.com/task/6466882336456704)):

```sh
gem install ronn test-unit --user-install --no-document
#<Thread:0x00007ffd2290aa20@/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/ronn-0.7.3.gem (Errno::EACCES)
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `write_binary'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
#<Thread:0x00007ffd2290ac78@/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/rdiscount-2.2.0.1.gem (Errno::EACCES)
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `write_binary'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/rdiscount-2.2.0.1.gem
Timed out!
```

I restarted all the Cirrus build jobs twice but this didn't help. Labelled urgent, as #3179,  #2969 and #3192 for example get [similar errors](https://cirrus-ci.com/task/5902035483885568).

@sanssecours Maybe related to 81e2d9d846f4fd09cb2bf65e356c2af058c64971?

**Comment by sanssecours** [comment]
> @sanssecours Maybe related to 81e2d9d?

I do not think so. The problem – as far as I can tell – is that installing Gems in the Cirrus macOS images [does not work without `sudo` anymore](https://github.com/cirruslabs/osx-images/issues/19), even if we specify the option `--user-install`. I already fixed this problem in my copy of the repo. Unfortunately there are other problems introduced by the latest changes to the macOS images. Currently I try to – at least temporarily – fix those issues too.

**Comment by markus2330** [comment]
@sanssecours thank you so much that you are fixing this!
