### ISSUE TITLE
Example App throws exception [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3757]
## Steps to Reproduce the Problem

```sh
cd examples/external/java/read-keys-example
gradle run
```

or 

```sh
cd examples/external/java/read-keys-example
mvn compile exec:java
```

## Expected Result

Example running without throwing an exception.

## Actual Result

```
Example started
Reading following keys:
server/port
spring/profiles/active
spring/datasource/type
spring/datasource/url
spring/datasource/username
spring/datasource/password
spring/jpa/database-platform
spring/jpa/database
spring/mail/host
spring/mail/port
jhipster/mail/from
jhipster/mail/base-url
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
org.libelektra.exception.InternalException: Sorry, module (null) issued error C01310:
Sorry, could not map error number '(null)'. Please report this incident at https://issues.libelektra.org/
Configfile: user:/temporary/errorkey

        at org.libelektra.exception.mapper.ExceptionMapperService.getMappedException(ExceptionMapperService.java:60)
        at org.libelektra.KDB.open(KDB.java:39)
        at org.libelektra.app.App.readKeys(App.java:59)
        at org.libelektra.app.App.loadConfigurationSettings(App.java:45)
        at org.libelektra.app.App.main(App.java:20)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:834)
Result:
null
Example terminated
```

## System Information

- Elektra Version: master
- Operating System: wsl2

**Comment by markus2330** [comment]
Thank you for reporting this problem! The error is probably some local problem, but its perfect that you have this problem, as it seems the error mapping in the Java binding is broken (it is probably untested as many errors like broken installation usually do not happen on the build server). Maybe you can find out via `kdb` what the error is and why this error code is not mapped.

**Comment by philippoppel** [comment]
is this an open issue I can look into?

**Comment by tucek** [comment]
I'll check whether this bug still exists
