### ISSUE TITLE
ASAN test_getenv fails on master

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4553]
Noticed in #4528 https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4528/16/pipeline

```

130/236 Test  #35: test_getenv ...................................***Failed    1.73 sec

[==========] Running 9 tests from 1 test suite.

[----------] Global test environment set-up.

[----------] 9 tests from GetEnv

[ RUN      ] GetEnv.NonExist

[       OK ] GetEnv.NonExist (4 ms)

[ RUN      ] GetEnv.ExistOverride

[       OK ] GetEnv.ExistOverride (61 ms)

[ RUN      ] GetEnv.ExistOverrideFallback

[       OK ] GetEnv.ExistOverrideFallback (24 ms)

[ RUN      ] GetEnv.ExistEnv

[       OK ] GetEnv.ExistEnv (28 ms)

[ RUN      ] GetEnv.ExistEnvFallback

[       OK ] GetEnv.ExistEnvFallback (52 ms)

[ RUN      ] GetEnv.ExistFallback

[       OK ] GetEnv.ExistFallback (57 ms)

[ RUN      ] GetEnv.ExistFallbackFallback

[       OK ] GetEnv.ExistFallbackFallback (70 ms)

[ RUN      ] GetEnv.OpenClose

[       OK ] GetEnv.OpenClose (100 ms)

[ RUN      ] GetEnv.OpenCloseFallback

[       OK ] GetEnv.OpenCloseFallback (71 ms)

[ DISABLED ] GetEnv.DISABLED_ArgvParam

[ DISABLED ] GetEnv.DISABLED_ArgvParamUninvolved

[ DISABLED ] GetEnv.DISABLED_ArgvParamVersion

[ DISABLED ] GetEnv.DISABLED_NameArgv0

[ DISABLED ] GetEnv.DISABLED_NameExplicit

[----------] 9 tests from GetEnv (480 ms total)



[----------] Global test environment tear-down

[==========] 9 tests from 1 test suite ran. (482 ms total)

[  PASSED  ] 9 tests.



  YOU HAVE 5 DISABLED TESTS





=================================================================

==8138==ERROR: LeakSanitizer: detected memory leaks



Direct leak of 64 byte(s) in 1 object(s) allocated from:

    #0 0x4a6762 in __interceptor_calloc (/home/jenkins/workspace/libelektra_PR-4528/build/bin/test_getenv+0x4a6762)

    #1 0x7fac45e3eeac in keyVNew /home/jenkins/workspace/libelektra_PR-4528/src/libs/elektra/key.c:160:14

    #2 0x7fac45e3ed8d in keyNew /home/jenkins/workspace/libelektra_PR-4528/src/libs/elektra/key.c:144:12

    #3 0x7fac45f0a3bf in elektraOpen /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/src/getenv.cpp:458:29

    #4 0x4db5ff in GetEnv_ExistOverrideFallback_Test::TestBody() /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/tests/test_getenv.cpp:31:2

    #5 0x553c44 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2599:10

    #6 0x553c44 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2635:14

    #7 0x514b02 in testing::Test::Run() /opt/gtest/googletest/src/gtest.cc:2674:5

    #8 0x516680 in testing::TestInfo::Run() /opt/gtest/googletest/src/gtest.cc:2853:11

    #9 0x5188f1 in testing::TestSuite::Run() /opt/gtest/googletest/src/gtest.cc:3012:30

    #10 0x539b48 in testing::internal::UnitTestImpl::RunAllTests() /opt/gtest/googletest/src/gtest.cc:5870:44

    #11 0x557803 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2599:10

    #12 0x557803 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2635:14

    #13 0x53885f in testing::UnitTest::Run() /opt/gtest/googletest/src/gtest.cc:5444:10

    #14 0x4e311c in RUN_ALL_TESTS() /opt/gtest/googletest/include/gtest/gtest.h:2293:73

    #15 0x4e311c in main /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/tests/main.cpp:24:12

    #16 0x7fac45922209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16



Direct leak of 64 byte(s) in 1 object(s) allocated from:

    #0 0x4a65cd in malloc (/home/jenkins/workspace/libelektra_PR-4528/build/bin/test_getenv+0x4a65cd)

    #1 0x7fac45e4ee01 in ksVNew /home/jenkins/workspace/libelektra_PR-4528/src/libs/elektra/keyset.c:237:22

    #2 0x7fac45e4ed6c in ksNew /home/jenkins/workspace/libelektra_PR-4528/src/libs/elektra/keyset.c:219:7

    #3 0x7fac45f0a3d8 in elektraOpen /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/src/getenv.cpp:459:26

    #4 0x4db5ff in GetEnv_ExistOverrideFallback_Test::TestBody() /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/tests/test_getenv.cpp:31:2

    #5 0x553c44 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2599:10

    #6 0x553c44 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2635:14

    #7 0x514b02 in testing::Test::Run() /opt/gtest/googletest/src/gtest.cc:2674:5

    #8 0x516680 in testing::TestInfo::Run() /opt/gtest/googletest/src/gtest.cc:2853:11

    #9 0x5188f1 in testing::TestSuite::Run() /opt/gtest/googletest/src/gtest.cc:3012:30

    #10 0x539b48 in testing::internal::UnitTestImpl::RunAllTests() /opt/gtest/googletest/src/gtest.cc:5870:44

    #11 0x557803 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2599:10

    #12 0x557803 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/gtest/googletest/src/gtest.cc:2635:14

    #13 0x53885f in testing::UnitTest::Run() /opt/gtest/googletest/src/gtest.cc:5444:10

    #14 0x4e311c in RUN_ALL_TESTS() /opt/gtest/googletest/include/gtest/gtest.h:2293:73

    #15 0x4e311c in main /home/jenkins/workspace/libelektra_PR-4528/src/bindings/intercept/env/tests/main.cpp:24:12

    #16 0x7fac45922209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16



[...]


SUMMARY: AddressSanitizer: 1964 byte(s) leaked in 43 allocation(s).
```

**Comment by markus2330** [comment]
fixed in #4560
