### ISSUE TITLE
testjna_gradle fails with: double free or corruption

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4980]
On master Jenkins builds now fail with:

```
35/293 Test  #35: testjna_gradle ................................***Failed    3.31 sec

double free or corruption (out)


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':libelektra:test'.

> Process 'Gradle Test Executor 1' finished with non-zero exit value 134

  This problem might be caused by incorrect test process configuration.

  Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.0.2/userguide/java_testing.html#sec:test_execution


* Try:

> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.


* Exception is:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':libelektra:test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	...
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

* Get more help at https://help.gradle.org/

BUILD FAILED in 3s
```

https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/1080/pipeline

**Comment by markus2330** [comment]
@tucek any idea? It cannot be related to #4972, can it?

**Comment by tucek** [comment]
> @tucek any idea? It cannot be related to #4972, can it?

Since #4972 only contains documentation, i cannot see any relevance...

**Comment by markus2330** [comment]
So maybe a Java upgrade?
