### ISSUE TITLE
Elektra hangs in kdbOpen

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4981]
## Steps to Reproduce the Problem

execute kdbOpen, either using `kdb get` or by starting an application using Elektra on a toml file with a missing quote:

```toml
test = "t
```

## Expected Result

Error about quote

## Actual Result

hangs forever

strace kdb or an application leads to:

```
stat64("/home/olimex/.cache/elektra", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
brk(0x7bec000)                          = 0x7bec000
access("/home/olimex/.cache/elektra/backend/", W_OK) = 0
openat(AT_FDCWD, "/home/olimex/.cache/elektra/backend//cache_cascading.mmap", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0600, st_size=9112, ...}) = 0
mmap2(NULL, 9112, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0xa708a000
close(3)                                = 0
stat64("/usr/share/elektra/specification/opensesame.spec", {st_mode=S_IFREG|0644, st_size=3412, ...}) = 0
stat64("/home/olimex/opensesame/.dir/opensesame.toml", 0xbebbbb88) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
stat64("/home/olimex/.config/opensesame.toml", {st_mode=S_IFREG|0600, st_size=957, ...}) = 0
stat64("/etc/kdb/opensesame.toml", 0xbebbbb88) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
openat(AT_FDCWD, "/usr/share/elektra/specification/opensesame.spec", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=3412, ...}) = 0
read(3, "# configuration specification fo"..., 4096) = 3412
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/home/olimex/.config/opensesame.toml", O_RDONLY) = 3
ioctl(3, TCGETS, 0xbebbbc10)            = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
fstat64(3, {st_mode=S_IFREG|0600, st_size=957, ...}) = 0
read(3, "debug.backtrace = \"full\"\ndebug.p"..., 8192) = 957
read(3, "", 4096)                       = 0
read(3, "", 8192)                       = 0
ioctl(3, TCGETS, 0xbebbaa18)            = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
read(3, "", 8192)                       = 0
ioctl(3, TCGETS, 0xbebbaa18)            = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
read(3, "", 8192)                       = 0
ioctl(3, TCGETS, 0xbebbaa18)            = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
read(3, "", 8192)                       = 0
ioctl(3, TCGETS, 0xbebbaa18)            = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
(endlessly repeated)
```

## System Information

- Elektra: 0.9.10
- Operating System: Linux armhf

## Further Log Files and Output

probably misleading stacktrace of first interruption of the process, probably unrelated to real problem:

```
#2  0xb6f9b488 in __GI__dl_catch_exception (exception=0xbeffe928, operate=0xb6fe3869 <dl_open_worker>, args=0xbeffe934) at dl-error-skeleton.c:208
#3  0xb6fe35cc in _dl_open (file=0x7df9b8 "libelektra-length.so", mode=-2147483646, caller_dlopen=0xb6c7e5a1 <elektraModulesLoad+116>, nsid=-2, argc=1, argv=0xbefff864, env=0xbefff86c)
    at dl-open.c:837
#4  0xb6b7cb60 in dlopen_doit (a=0xbeffeb94) at dlopen.c:66
#5  0xb6f9b488 in __GI__dl_catch_exception (exception=exception@entry=0xbeffeb50, operate=0xb6b7cb09 <dlopen_doit>, args=args@entry=0xbeffeb94) at dl-error-skeleton.c:208
#6  0xb6f9b51c in __GI__dl_catch_error (objname=0x7d7a64, errstring=0x7d7a68, mallocedp=0x7d7a60, operate=<optimized out>, args=0xbeffeb94) at dl-error-skeleton.c:227
#7  0xb6b7d226 in _dlerror_run (operate=<optimized out>, args=args@entry=0xbeffeb94) at dlerror.c:170
#8  0xb6b7cbe6 in __dlopen (file=file@entry=0x7df9b8 "libelektra-length.so", mode=mode@entry=2) at dlopen.c:87
#9  0xb6c7e5a0 in elektraModulesLoad (modules=modules@entry=0x7d7608, name=name@entry=0x7e3ee8 "length", errorKey=errorKey@entry=0x7d73d8) at /mnt/data/libelektra/src/libs/loader/dl.c:80
#10 0xb6c61ed4 in elektraPluginOpen (name=0x7e3ee8 "length", modules=modules@entry=0x7d7608, config=0x7e41c0, errorKey=errorKey@entry=0x7d73d8) at /mnt/data/libelektra/src/libs/elektra/plugin.c:268
#11 0xb6c620c8 in elektraProcessPlugins (plugins=plugins@entry=0x7e2e94, modules=modules@entry=0x7d7608, referencePlugins=referencePlugins@entry=0x7df5e0, config=config@entry=0x7d9dd8,
    systemConfig=systemConfig@entry=0x7e3830, global=global@entry=0x7d75b8, errorKey=errorKey@entry=0x7d73d8) at /mnt/data/libelektra/src/libs/elektra/plugin.c:180
#12 0xb6c5e214 in backendOpen (elektraConfig=0x7e2ac0, modules=modules@entry=0x7d7608, global=0x7d75b8, errorKey=errorKey@entry=0x7d73d8) at /mnt/data/libelektra/src/libs/elektra/backend.c:209
#13 0xb6c6151c in mountOpen (kdb=0x7d7420, config=config@entry=0x7d76b8, modules=0x7d7608, errorKey=errorKey@entry=0x7d73d8) at /mnt/data/libelektra/src/libs/elektra/mount.c:61
#14 0xb6c5fd74 in kdbOpen (contract=<optimized out>, errorKey=0x7d73d8) at /mnt/data/libelektra/src/libs/elektra/kdb.c:522
#15 0x00450518 in elektra::kdb::KDB::open ()
```

**Comment by markus2330** [comment]
The problem was a missing quote in the toml file:

```toml
test = "
```

Having this, Elektra hangs endlessly.
