### ISSUE TITLE
spec plugin Segmentation fault

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#506]
Made a fresh install:

```
kdb global-mount
kdb spec-mount /test
kdb set /test ""
kdb set spec/test ""
kdb setmeta spec/test require 1
```
leads to
`Segmentation fault (core dumped)`

I am not sure if it is possible to specify rules for the mount point.

The segfault appears in 'keyNameToMatchingString'.

**Comment by markus2330** [comment]
Thank you for reporting. I can reproduce it. Stacktrace:
```
#0  keyNameToMatchingString (key=key@entry=0x1f45ca0) at /home/markus/Projekte/Elektra/current/src/plugins/spec/spec.c:63
#1  0x00007fba222bb843 in doGlobbing (parentKey=parentKey@entry=0x201d980, returned=returned@entry=0x1f45e00, specKS=specKS@entry=0x1f45d30, ch=ch@entry=0x1f45cf0, dir=dir@entry=SET) at /home/markus/Projekte/Elektra/current/src/plugins/spec/spec.c:636
#2  0x00007fba222bc683 in elektraSpecSet (handle=<optimized out>, returned=0x1f45560, parentKey=0x201d980) at /home/markus/Projekte/Elektra/current/src/plugins/spec/spec.c:846
#3  0x00007fba26d009d5 in runPlugins (pluginKS=0x1f45d10, pluginKS@entry=0x1f51780, modules=0x2f, plugins=0x0, configOrig=0x0, returned=0x0, returned@entry=0x1f45560, parentKey=0x1f45d10, parentKey@entry=0x201d980, op=SET, traversalFunction=0x7fba28da4070 <ksPop>)
    at /home/markus/Projekte/Elektra/current/src/plugins/list/list.c:279
#4  0x00007fba26d00dbf in elektraListSet (handle=<optimized out>, returned=0x1f45560, parentKey=0x201d980) at /home/markus/Projekte/Elektra/current/src/plugins/list/list.c:355
#5  0x00007fba28b907e9 in elektraSetPrepare (hook=0x1ebb960, errorKey=<synthetic pointer>, parentKey=0x201d980, split=0x1f467d0) at /home/markus/Projekte/Elektra/current/src/libs/elektra/kdb.c:791
#6  kdbSet (handle=0x1e6e1f0, ks=0x1f44920, parentKey=0x201d980) at /home/markus/Projekte/Elektra/current/src/libs/elektra/kdb.c:1053
#7  0x0000000000422128 in set (parentKey=..., returned=<synthetic pointer>, this=0x1e6e188) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/kdb.hpp:225
#8  MetaSetCommand::execute (this=0x1e6e180, cl=...) at /home/markus/Projekte/Elektra/current/src/tools/kdb/metaset.cpp:72
#9  0x0000000000416ab5 in main (argc=5, argv=0x7fff180ee1b8) at /home/markus/Projekte/Elektra/current/src/tools/kdb/main.cpp:147
```

**Comment by markus2330** [comment]
@tom-wa It seems that name is a null pointer. Debug Stacktrace:
```
#0  0x00007fa687b62d0d in keyNameToMatchingString (key=0x970b80) at /home/markus/Projekte/Elektra/current/src/plugins/spec/spec.c:63
        ptr = 0x0
        arrayCount = 0 '\000'
        name = 0x0
        pattern = 0x0
        dst = 0x970bf9 ""
#1  0x00007fa687b64989 in doGlobbing (parentKey=0xa488e0, returned=0x970ce0, specKS=0x970c10, ch=0x970bd0, dir=SET) at /home/markus/Projekte/Elektra/current/src/plugins/spec/spec.c:636
        matchKey = 0x970b80
        require = 1
        pattern = 0x970bf0 "spec"
        specKey = 0x9708f0
        cur = 0x0
        ret = 1
```
