### ISSUE TITLE
ini: Segfault for array feature

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#556]
Given the setup as described in #355, appending keys to array now segfaults:

```
#0  keyString (key=0x21) at /home/markus/Projekte/Elektra/current/src/libs/elektra/keyvalue.c:197
197             if (!key->data.c)
(gdb) bt
#0  keyString (key=0x21) at /home/markus/Projekte/Elektra/current/src/libs/elektra/keyvalue.c:197
#1  0x00007f4f5786c9b2 in iniWriteKeySet (config=0xc6d600, returned=<optimized out>, parentKey=<optimized out>, fh=0xc3f520)
    at /home/markus/Projekte/Elektra/current/src/plugins/ini/ini.c:1210
#2  elektraIniSet (handle=<optimized out>, returned=<optimized out>, parentKey=<optimized out>) at /home/markus/Projekte/Elektra/current/src/plugins/ini/ini.c:1473
#3  0x00007f4f59f4c253 in elektraSetPrepare (hook=0xc22b50, errorKey=<synthetic pointer>, parentKey=0xd82ab0, split=0xc71e90)
    at /home/markus/Projekte/Elektra/current/src/libs/elektra/kdb.c:751
#4  kdbSet (handle=0xc201f0, ks=0xc59400, parentKey=0xd82ab0) at /home/markus/Projekte/Elektra/current/src/libs/elektra/kdb.c:1010
#5  0x000000000042088a in set (parentKey=..., returned=<synthetic pointer>, this=0xc20188) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/kdb.hpp:226
#6  SetCommand::execute (this=0xc20180, cl=...) at /home/markus/Projekte/Elektra/current/src/tools/kdb/set.cpp:100
#7  0x0000000000416b75 in main (argc=4, argv=0x7ffee42981f8) at /home/markus/Projekte/Elektra/current/src/tools/kdb/main.cpp:145
```

bt full (shortened):
```
#0  keyString (key=0x21) at /home/markus/Projekte/Elektra/current/src/libs/elektra/keyvalue.c:197
No locals.
#1  0x00007f4f5786c9b2 in iniWriteKeySet (config=0xc6d600, returned=<optimized out>, parentKey=<optimized out>, fh=0xc3f520)
    at /home/markus/Projekte/Elektra/current/src/plugins/ini/ini.c:1210
        string = <optimized out>
        j = 7
        name = 0xcee680 "a"
        i = <optimized out>
        keyArray = 0xcee640
        sectionKey = 0xc3eec0
        ret = 1
        removeSectionKey = 1
#2  elektraIniSet (handle=<optimized out>, returned=<optimized out>, parentKey=<optimized out>) at /home/markus/Projekte/Elektra/current/src/plugins/ini/ini.c:1473
        errnosave = 0
        ret = 1
        fh = 0xc3f520
        orderKey = <optimized out>
        pluginConfig = 0xc6d600
```

Please add some testcases which segfault now and demonstrate the fix.

**Comment by tom-wa** [comment]
can you give me the commands/steps you've used ?
i've just mounted the array.ini from the ini testfiles and tried it:
```
% cat /tmp/array.ini
[sec]
a = 1
a = 2
a = 3
a = 4
 % kdb set system/arraytest/sec/a/#4 test
 % cat /tmp/array.ini
[sec]
a = 1
a = 2
a = 3
a = 4
a = test
```

**Comment by markus2330** [comment]
I hoped the backtrace will already help you.

```
# kdb mount
test.ini on system/ini/array with name system/ini/array
$ cat test.ini
[sec]
a = 1
a = x
$ kdb set system/ini/array/a/#2 NEW
Create a new key system/ini/array/a/#2 with string NEW
zsh: segmentation fault (core dumped)  noglob kdb set system/ini/array/a/#2 NEW
```

**Comment by tom-wa** [comment]
ah now i see the problem: 
it should be array/sec/a 
i really need some error handling with those inputs though, thanks for reporting

**Comment by markus2330** [comment]
Yes, please add error handling, a seg fault is really a no-go.

**Comment by markus2330** [comment]
See #185 for an effective technique to find such problems.
