### ISSUE TITLE
list: segfault if plugin is not present

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#627]
It seems like we have a regression (we would really need shell recorder testcases for global plugins). The list plugin again crashes when a plugin is unable to load:

```
(gdb) bt
#0  0x00007f745227ed00 in ?? ()
#1  0x00007f7456ed3855 in runPlugins (pluginKS=0x1622f80, pluginKS@entry=0x1623780, modules=0x1621cd0, plugins=0x1568ef0, configOrig=0x1623a00, returned=0x0, returned@entry=0x1621cd0, parentKey=0x1623b60, parentKey@entry=0x1568ef0, op=GET, 
    traversalFunction=0x7f745917bf90 <ksNext>) at /home/markus/Projekte/Elektra/current/src/plugins/list/list.c:278
#2  0x00007f7456ed3b2b in elektraListGet (handle=<optimized out>, returned=0x1621cd0, parentKey=0x1568ef0) at /home/markus/Projekte/Elektra/current/src/plugins/list/list.c:336
#3  0x00007f7458f668bf in kdbGet (handle=0x1568fc0, ks=0x1621cd0, parentKey=0x1568ef0) at /home/markus/Projekte/Elektra/current/src/libs/elektra/kdb.c:719
#4  0x0000000000432593 in get (parentKey=..., returned=<synthetic pointer>, this=0x7ffffd143e30) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/kdb.hpp:183
#5  get (keyname="/sw/elektra/kdb/#0/current/", returned=<synthetic pointer>, this=0x7ffffd143e30) at /home/markus/Projekte/Elektra/current/src/bindings/cpp/include/kdb.hpp:166
#6  Cmdline::Cmdline (this=0x7ffffd144160, argc=3, argv=0x7ffffd144338, command=0x14a0180) at /home/markus/Projekte/Elektra/current/src/tools/kdb/cmdline.cpp:271
#7  0x0000000000416de9 in main (argc=3, argv=0x7ffffd144338) at /home/markus/Projekte/Elektra/current/src/tools/kdb/main.cpp:115
```

**Comment by markus2330** [comment]
And there is also a memory leak with the list/spec plugin present:
```
==3151==    at 0x4C28C20: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3151==    by 0x53B608D: elektraSpecSet (spec.c:1227)
==3151==    by 0x5343BC4: runPlugins (list.c:285)
==3151==    by 0x5343FC4: elektraListSet (list.c:353)
==3151==    by 0x52F9CEE: elektraSetPrepare (kdb.c:877)
==3151==    by 0x52F9CEE: kdbSet (kdb.c:1122)
==3151==    by 0x4184A8: set (kdb.hpp:227)
==3151==    by 0x4184A8: MergingKDBTest_HandlesUnconflictingKeySets_Test::TestBody() (testtool_mergingkdb.cpp:73)
==3151==    by 0x447A41: void testing::internal::HandleExceptionsInMethodIfSupported&amp;lt;testing::Test, void&amp;gt;(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2134)
==3151==    by 0x43E8C3: testing::Test::Run() (gtest.cc:2151)
==3151==    by 0x43E9E7: testing::TestInfo::Run() [clone .part.372] (gtest.cc:2326)
==3151==    by 0x43EAE9: Run (gtest.cc:2301)
==3151==    by 0x43EAE9: testing::TestCase::Run() [clone .part.373] (gtest.cc:2444)
==3151==    by 0x43EED4: Run (gtest.cc:4281)
==3151==    by 0x43EED4: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:4315)
==3151==    by 0x447F36: bool testing::internal::HandleExceptionsInMethodIfSupported&amp;lt;testing::internal::UnitTestImpl, bool&amp;gt;(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2134)
==3151==    by 0x43F0A8: testing::UnitTest::Run() (gtest.cc:3929)
==3151==    by 0x417ADF: RUN_ALL_TESTS (gtest.h:2288)
==3151==    by 0x417ADF: main (gtest_main.cc:37)

```
