### ISSUE TITLE
FreeBSD: testpy2_kdb.py fails

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#714]
Seems very related to #631. `testpy2_kdb.py` is failing because `dlopen` failed.

```
 66/118 Test  #66: test_kdb.py ........................***Failed    0.08 sec
..EEEE
======================================================================
ERROR: test_ctor (__main__.KDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mpranj/workspace/libelektra/src/bindings/swig/python/tests/test_kdb.py", line 25, in test_ctor
    self.assertIsInstance(kdb.KDB(), kdb.KDB)
  File "/home/mpranj/workspace/libelektra/build/src/bindings/swig/python/kdb.py", line 1742, in __init__
    _kdb.KDB_swiginit(self, _kdb.new_KDB(*args))
kdb.KDBException: 1 Warning was issued:
 Warning number: 1
    Description: could not load module, dlopen failed
    Ingroup: modules
    Module: dl
    At: /home/mpranj/workspace/libelektra/src/libs/loader/dl.c:82
    Reason: of module: libelektra-resolver.so, because: Shared object "libelektra-resolver.so" not found, required by "python3"
    Mountpoint:
    Configfile:
Error (#40) occurred!
Description: Failed to open default backend (see warnings for more information)
Ingroup: kdb
Module:
At: /home/mpranj/workspace/libelektra/src/libs/elektra/kdb.c:282
Reason: could not open default backend
Mountpoint:
Configfile:
```

[testpy2_kdb.py.txt](https://github.com/ElektraInitiative/libelektra/files/260196/testpy2_kdb.py.txt)

**Comment by markus2330** [comment]
Thanks, isn't it a complete duplicate?

Is it also broken when the installed Elektra was built with `TARGET_PLUGIN_FOLDER` as an empty string? And can you check the RPATH `readelf -a lib/libelektra-core.so.0.8.16 | grep RPATH` (see also #631)

**Comment by mpranj** [comment]
on FreeBSD I get:
` 0x000000000000000f (RPATH)              Library rpath: [::::::::::::::::::::::]`

**Comment by markus2330** [comment]
Maybe it is easier to investigate the issue on FreeBSD than on Mac OS X?
