### ISSUE TITLE
gtest invalid vaargs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#741]
## Current behavior

As suggested I implemented a run-time check if wrong arguments are passed to keyNew.
One place that passes invalid arguments is src/bindings/glib/tests/testglib_key.c:

```
gdb bin/testglib_key core
#0  0x00007f26b1345067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f26b1346448 in __GI_abort () at abort.c:89
#2  0x00007f26b133e266 in __assert_fail_base (fmt=0x7f26b286cf7e <error: Cannot access memory at address 0x7f26b286cf7e>, assertion=assertion@entry=0x7f26b1e2b760 "0 && \"Unknown option in keyVInit\"", 
    file=file@entry=0x7f26b1e2b718 "/home/markus/Projekte/Elektra/current/src/libs/elektra/keyhelpers.c", line=line@entry=433, function=function@entry=0x7f26b1e2b782 <__PRETTY_FUNCTION__.4215> "keyVInit") at assert.c:92
#3  0x00007f26b133e312 in __GI___assert_fail (assertion=assertion@entry=0x7f26b1e2b760 "0 && \"Unknown option in keyVInit\"", file=file@entry=0x7f26b1e2b718 "/home/markus/Projekte/Elektra/current/src/libs/elektra/keyhelpers.c", line=line@entry=433, 
    function=function@entry=0x7f26b1e2b782 <__PRETTY_FUNCTION__.4215> "keyVInit") at assert.c:101
#4  0x00007f26b1e24fda in keyVInit (key=0x24fa0d0, name=name@entry=0x405a07 "user/key", va=va@entry=0x7ffd8f254088) at /home/markus/Projekte/Elektra/current/src/libs/elektra/keyhelpers.c:433
#5  0x00007f26b22479d1 in gelektra_key_new (name=name@entry=0x405a07 "user/key") at /home/markus/Projekte/Elektra/current/src/bindings/glib/gelektra-key.c:121
#6  0x0000000000402e9c in create_global_keys () at /home/markus/Projekte/Elektra/current/src/bindings/glib/tests/testglib_key.c:85
#7  main (argc=<optimized out>, argv=0x7ffd8f254398) at /home/markus/Projekte/Elektra/current/src/bindings/glib/tests/testglib_key.c:289

Unknown option in keyVInit: 65536
testglib_key: /home/markus/Projekte/Elektra/current/src/libs/elektra/keyhelpers.c:433: keyVInit: Zusicherung »0 && "Unknown option in keyVInit"« nicht erfüllt.
zsh: abort (core dumped)  bin/testglib_key
```

## Expected behavior

Get a nice exception/error when passing invalid flags (if possible).

**Comment by markus2330** [comment]
Do you need more info here?

**Comment by markus2330** [comment]
Closed because of low priorty.
